name: CI-feature-branch
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: ["*", "!main", "!master", "!skip/*"]
  workflow_dispatch:
jobs:
  webapp:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install frontend
        working-directory: frontend
        run: |
          npm install
      - name: Test frontend
        working-directory: frontend
        run: |
          npm test
      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build
      - name: Install backend
        working-directory: backend
        run: |
          npm install
      - name: Test backend
        working-directory: backend
        run: |
          npm test
      - name: Prepare backend Lambda code
        working-directory: backend
        run: |
          npm run install-build
      - name: Install infra
        working-directory: infra
        run: |
          npm install
      - name: Build infra
        working-directory: infra
        run: npm run build
      - name: Test infra
        working-directory: infra
        run: |
          npm test
      - name: Configure AWS Credentials, dev env
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          aws-region: us-east-1
      - name: Deploy the webapp stack to the dev account
        working-directory: infra
        run: |
          npm run deploy-webapp
  itest:
    runs-on: ubuntu-latest
    needs: [webapp]
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install itest
        working-directory: itest
        run: |
          npm install
      - name: Configure AWS Credentials, dev env
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          aws-region: us-east-1
      - name: Run itest
        env:
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
        working-directory: itest
        run: |
          npm run itest
  itest-kate:
    runs-on: ubuntu-latest
    needs: [webapp]
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install itest
        working-directory: itest
        run: |
          npm install
      - name: Configure AWS Credentials, dev env
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          aws-region: us-east-1
      - name: Run itest for Kate
        env:
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
        working-directory: itest
        run: |
          npm run itest -- App.kate.itest.cjs